apiVersion: v1
kind: Service
metadata:
  name: app-external-service
spec:
  type: LoadBalancer # External access
  selector:
    app: python-web # Podokra mutat, nem deploymentre!
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 3000
