apiVersion: v1
kind: Service
metadata:
  name: postgres-internal-service 
spec:
  type: ClusterIP # Internal access
  selector:
    app: database # A service-nek a podokat kell tudnia, hogy melyik podokat kell elérnie
  ports:
    - port: 5432       
      targetPort: 5432 
